[package]
name = "multiple_joysticks_mobile"
version = "0.1.0"
edition = "2021"

[lib]
name = "multiple_joysticks_mobile"
crate-type = ["staticlib", "cdylib"]

[dependencies]
bevy = "0.11.0"
virtual_joystick = { path = "../../" }
